### ISSUE TITLE
StyleTransfer problem

### ISSUE THREAD

**Issue by Jumpat** [LiYingwei/ShapeTextureDebiasedTraining#6]
Hello, when I tried to reproduce your work, the output of the style transfer module often has noise, I have tried to use a smaller alpha as the style transformation parameter, but it doesn't work at all. I want to know whether you have met this problem, and if so how can you solve this.
Thanks for your reading!
![see2](https://user-images.githubusercontent.com/49474962/115853782-1f0fae80-a45c-11eb-83f4-753174ece8f5.jpg)
![st_8](https://user-images.githubusercontent.com/49474962/115853792-20d97200-a45c-11eb-9b7a-d7eb773ed987.jpg)

**Comment by wiseManCanSeeIt** [comment]
> Hello, when I try to reproduce your work, the output of the style transfer module often has noise, I have tried to use a smaller alpha as the style transformation parameter, but it doesn't work at all. I want to know whether you have met this problem, and if so how can you solve this.
> Thanks for your reading!
> ![see2](https://user-images.githubusercontent.com/49474962/115853782-1f0fae80-a45c-11eb-83f4-753174ece8f5.jpg)
> ![st_8](https://user-images.githubusercontent.com/49474962/115853792-20d97200-a45c-11eb-9b7a-d7eb773ed987.jpg)

**Comment by LiYingwei** [comment]
Thanks for your interest! I think this noise might because the output images are slightly beyond the image space, which causes an overflow issue -- I remember some values of the pixels are larger than 1. The noise you see is probably due to these pixels are overflow, and then truncated by the visualization tool.

Therefore, it is necessary to rescale the value of the image back to [0, 1] before visualization. However, when using these generated images as training data, I don't rescale them back to [0, 1] image space (unlike the visualization tool, the preprocessing functions won't truncate the overflow pixels)

For the performance issue, could you provide more details about what kinds of dataset/model/training strategies are you using? Maybe I can find some other issues.

Thanks,
Yingwei

**Comment by Jumpat** [comment]
Thanks for your reply! 
The dataset I'm using is just a random small subset of imageNet, and the lemon and chimpanzee you used in your paper are found in imageNet with my own hands😂. 
So in fact this noise doesn't have to be removed in the real train process. I will try your method and see whether it help. I will give you some feedback after that!

**Comment by Jumpat** [comment]
Thanks very much for your help. Your method is proved useful, which really helps me a lot!
Wish you all the best~
